#default port number
server.port=8087
#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=telbot
spring.datasource.username=postgres
spring.datasource.password=4180
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database=postgresql
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.default_schema=telbot
#Flyway
spring.flyway.url=jdbc:postgresql://localhost:5432/postgres
spring.flyway.user=postgres
spring.flyway.password=4180
spring.flyway.default-schema=telbot

#Telegram
interval-in-cron-morning =0 0 6 * * ?
interval-in-cron-evening =0 0 18 * * ?

botname = i113_assistant_bot
bottoken = 6130769269:AAHfY8rS5tB2kSEo0uGwoCgG6SKba797uc8
botrootchatid = 425222583

spring.application.name=telbot-service
eureka.client.service-url.defaultZone=http://localhost:8761/eureka