name: telbot-action-process
env:
  APPLICATION_NAME : "Telbot"
on: 
  push:
    branches: 
      - master

jobs:
  UpdateTelbotService:
    runs-on: self-hosted
    
    steps:
      - name: PrintAppData
        run : |
          echo "Application name: ${{ env.APPLICATION_NAME}}"
          
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          clean: 'false'

      - name: Maven Telbot clean-build
        run : |
          mvn clean
          mvn install  

      - name: Docker Telbot update
        run : |
          bash i113_telbot_update.sh   

      - name: Docker Compose up
        run : |
          cd /home/ditar/actions-runner/elli_project_work/
          docker compose up --detach   

          
                 
